from typing import Any


class ILogger:
    def debug(self, message: str, **kwargs: Any) -> None: ...

    def info(self, message: str, **kwargs: Any) -> None: ...

    def warning(self, message: str, **kwargs: Any) -> None: ...

    def error(self, message: str, **kwargs: Any) -> None: ...
