from typing import Any

from src.domain.models import ItemFeatures, ItemsCollection, UserFeatures, UserItemFeatures


class IDbRepository:
    async def get_item_features(
        self, identifiers: list[int], *args: Any, **kwargs: dict[str, Any]
    ) -> list[ItemFeatures]: ...

    async def save_item_features(self, collection: list[ItemFeatures]) -> None: ...

    async def save_collection(self, collection: ItemsCollection) -> None: ...

    async def get_collection(self, collection_name: str) -> ItemsCollection: ...

    async def save_user_item_features(self, user_item_features: list[UserItemFeatures]) -> None: ...

    async def get_user_item_features(
        self, user_id: int, identifiers: list[int], features: list[str]
    ) -> list[UserItemFeatures]: ...

    async def get_item_feature(self, identifier: int) -> ItemFeatures: ...

    async def save_user_features(self, user_feature: UserFeatures) -> None: ...

    async def get_user_features(self, user_id: int, features: list[str]) -> UserFeatures: ...
